### ISSUE TITLE
`Downloads.download` prints `Unhandled Task ERROR: StackOverflowError:` and then hangs indefinitely

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaLang/Downloads.jl#163]
When running the [`generate_historical_stdlibs.jl` script](https://github.com/JuliaLang/Pkg.jl/blob/master/ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl), I get `Unhandled Task ERROR: StackOverflowError:`, and then it hangs indefinitely.

Here are the steps to reproduce under `rr`:
```shell
git clone https://github.com/JuliaLang/Pkg.jl.git
cd Pkg.jl
wget https://raw.githubusercontent.com/JuliaLang/julia/master/.buildkite/utilities/rr/rr_capture.jl
export JULIA_DEPOT_PATH=$(mktemp -d)
export JULIA_PROJECT="ext/HistoricaStdlibGenerator"
julia -e 'import Pkg; Pkg.instantiate()'
export JULIA_TEST_RR_TIMEOUT=10 # 10 minutes
while julia rr_capture.jl julia ext/HistoricaStdlibGenerator/generate_historical_stdlibs.jl; do :; done
```

Here's the error:
```
rr: Saving execution to trace directory `/home/dilum/Desktop/Pkg.jl/temp_for_rr/jl_ebxdQF/rr_traces/julia-0'.
[ Info: Downloading versions.json...
[ Info: Identified 25 versions to try...
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.0-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.1-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.2-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.3-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.4-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.0/julia-1.0.5-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.0-linux-x86_64.tar.gz
[ Info: Downloading https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
Unhandled Task ERROR: StackOverflowError:


Process timed out (with a timeout of 10 minutes). Signalling `rr` for force-cleanup!
`rr` returned 0, packing and uploading traces...
rr: Packed trace directory `/home/dilum/Desktop/Pkg.jl/temp_for_rr/jl_ebxdQF/rr_traces/julia-0'.
Read : 443 MB ==> 38%[ Info: The `rr` trace file has been saved to: /home/dilum/Desktop/Pkg.jl/dumps/rr--build_----commit_--2021_11_05_11_26_00.tar.zst
/*stdin*\            : 39.97%   (482458112 => 192818618 bytes, /home/dilum/Desktop/Pkg.jl/dumps/rr--build_----commit_--2021_11_05_11_26_00.tar.zst)
[ Info: Finished running the command under rr
┌ Info:
│   process.exitcode = 0
└   process.termsignal = 15
```

I have the `rr` trace. Let me know if you want me to send it to you.

**Comment by StefanKarpinski** [comment]
@vtjnash, would you mind taking a look at this since I doubt I'll be able to make heads or tails of it.

**Comment by vtjnash** [comment]
Looks like a Multi.jl usage error. Also, perhaps you're supposed to call `Curl_set_in_callback` inside any callbacks?
```c
...
#46 0x00007f5365f05360 in jfptr_timer_callback_18799.clone_1 () at channels.jl:331
#47 0x00007f537a13aa0a in _jl_invoke (world=31709, mfunc=<optimized out>, nargs=3, args=0x7f5310665330, F=0x7f53671fdcf0 <jl_system_image_data+10021424>)
    at /buildworker/worker/package_linux64/build/src/gf.c:2256
#48 ijl_apply_generic (F=<optimized out>, args=0x7f5310665330, nargs=<optimized out>) at /buildworker/worker/package_linux64/build/src/gf.c:2438
#49 0x00007f536592677f in jlcapi_timer_callback_18888.clone_1 () at locks-mt.jl:90
#50 0x00007f531edf074c in Curl_update_timer () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#51 0x00007f531edf2a0e in curl_multi_socket_action () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#52 0x00007f5365f00fea in curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:47
#53 curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:55
#54 macro expansion () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28
#55 japi1_do_multi_18962 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:114
#56 0x00007f5365f051b3 in julia_timer_callback_18798 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:127
#57 0x00007f5365f05360 in jfptr_timer_callback_18799.clone_1 () at channels.jl:331
#58 0x00007f537a13aa0a in _jl_invoke (world=31709, mfunc=<optimized out>, nargs=3, args=0x7f53106656b0, F=0x7f53671fdcf0 <jl_system_image_data+10021424>)
    at /buildworker/worker/package_linux64/build/src/gf.c:2256
#59 ijl_apply_generic (F=<optimized out>, args=0x7f53106656b0, nargs=<optimized out>) at /buildworker/worker/package_linux64/build/src/gf.c:2438
#60 0x00007f536592677f in jlcapi_timer_callback_18888.clone_1 () at locks-mt.jl:90
#61 0x00007f531edf074c in Curl_update_timer () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#62 0x00007f531edf2a0e in curl_multi_socket_action () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#63 0x00007f5365f00fea in curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:47
#64 curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:55
#65 macro expansion () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28
#66 japi1_do_multi_18962 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:114
#67 0x00007f5365f051b3 in julia_timer_callback_18798 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:127
#68 0x00007f5365f05360 in jfptr_timer_callback_18799.clone_1 () at channels.jl:331
#69 0x00007f537a13aa0a in _jl_invoke (world=31709, mfunc=<optimized out>, nargs=3, args=0x7f5310665a30, F=0x7f53671fdcf0 <jl_system_image_data+10021424>)
    at /buildworker/worker/package_linux64/build/src/gf.c:2256
#70 ijl_apply_generic (F=<optimized out>, args=0x7f5310665a30, nargs=<optimized out>) at /buildworker/worker/package_linux64/build/src/gf.c:2438
#71 0x00007f536592677f in jlcapi_timer_callback_18888.clone_1 () at locks-mt.jl:90
#72 0x00007f531edf074c in Curl_update_timer () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#73 0x00007f531edf2a0e in curl_multi_socket_action () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#74 0x00007f5365f00fea in curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:47
#75 curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:55
#76 macro expansion () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28
#77 japi1_do_multi_18962 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:114
#78 0x00007f5365f051b3 in julia_timer_callback_18798 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:127
#79 0x00007f5365f05360 in jfptr_timer_callback_18799.clone_1 () at channels.jl:331
#80 0x00007f537a13aa0a in _jl_invoke (world=31709, mfunc=<optimized out>, nargs=3, args=0x7f5310665db0, F=0x7f53671fdcf0 <jl_system_image_data+10021424>)
    at /buildworker/worker/package_linux64/build/src/gf.c:2256
#81 ijl_apply_generic (F=<optimized out>, args=0x7f5310665db0, nargs=<optimized out>) at /buildworker/worker/package_linux64/build/src/gf.c:2438
#82 0x00007f536592677f in jlcapi_timer_callback_18888.clone_1 () at locks-mt.jl:90
#83 0x00007f531edf074c in Curl_update_timer () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#84 0x00007f531edf2a0e in curl_multi_socket_action () from target:/home/dilum/.asdf/installs/julia/nightly/bin/../lib/julia/libcurl.so
#85 0x00007f5365f00fea in curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:47
#86 curl_multi_socket_action () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Curl.jl:55
#87 macro expansion () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/utils.jl:28
#88 japi1_do_multi_18962 () at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.8/Downloads/src/Curl/Multi.jl:114
...
```
Correct usage is exemplified here: https://github.com/curl/curl/blob/master/docs/examples/multi-uv.c#L165-L167
I'll make a PR to make this repo match the example.
